#!/usr/bin/env ruby

require 'url_smoker'

@sites = []
def smoke
    url_count = @sites.map {|site| site.test_cases.length }.reduce(:+)
    puts "Smoking #{@sites.length} sites and #{url_count} URLs"
    @sites.each do |site|
        UrlSmoker::run_tests site
        puts "--------------"
    end
end

ARGV.each do |file| 
    @sites = UrlSmoker::DSL.load file
end

smoke